name: Build and release

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Cleanup working dir
        run: rm -rfv ./*

      - name: Clone repo (needed for contribs)
        run: git clone https://github.com/OXRS-IO/OXRS-IO-TouchPanel-WEB-APP.git ./

      - name: NPM I
        run: npm ci

      - name: NPM Build
        run: npm run build

      - name: Custom domain - GitHub Pages
        run: echo 'touch.oxrs.io' > ./dist/CNAME
      
      - name: Deploy to GitHub Pages
        if: success()
        run: |
          npx gh-pages --dist dist --cname touch.oxrs.io --force-ssl false
