name: Build and release

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Cleanup working dir
        run: rm -rfv ./*

      - name: Clone repo (needed for contribs)
        run: git clone https://github.com/OXRS-IO/OXRS-IO-TouchPanel-WEB-APP.git ./

      - name: NPM I
        run: npm ci

      - name: NPM Build
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: false
          enable_jekyll: false
          cname: touch.oxrs.io
          cname_target: your-github-username.github.io
